changes componen multiselect
titarenko/buhoi-ui pull request #1
Opened 2017-03-21 15:25 UTC by akhll

- add label 
- add default value for variable selectedItems

2017-03-23 13:42 UTC, titarenko requested changes

2017-03-23 13:42 UTC, titarenko commented on components/list/component.jsx
> +function NoToolbar () {}
{
}

2017-03-23 13:42 UTC, titarenko commented on components/multiselect/index.jsx
> +	const { resource, label, query, suggestedItems, selectedSuggestionIndex, selectedItems = [], dispatch } = props
`selectedItems = []` - move to reducer

2017-12-26 12:29 UTC, akhll commented
not relevant

2017-12-26 12:29 UTC, closed without merging